In [1]:
import numpy as np

In [2]:
my_list = [-1,0,1]

In [3]:
my_list, type(my_list)

([-1, 0, 1], list)

In [4]:
my_array = np.array(my_list)

In [5]:
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np_matrix = np.array(my_matrix)

In [8]:
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

In [12]:
np.linspace(0,15,30,retstep=True)

(array([ 0.        ,  0.51724138,  1.03448276,  1.55172414,  2.06896552,
         2.5862069 ,  3.10344828,  3.62068966,  4.13793103,  4.65517241,
         5.17241379,  5.68965517,  6.20689655,  6.72413793,  7.24137931,
         7.75862069,  8.27586207,  8.79310345,  9.31034483,  9.82758621,
        10.34482759, 10.86206897, 11.37931034, 11.89655172, 12.4137931 ,
        12.93103448, 13.44827586, 13.96551724, 14.48275862, 15.        ]),
 0.5172413793103449)

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(3,2)

array([[0.74478669, 0.72858426],
       [0.35218626, 0.73667472],
       [0.03312898, 0.92422133]])

In [19]:
np.random.randn(4,4)

array([[ 1.11779069, -1.14267386, -0.57654243, -0.11903813],
       [-0.58775116, -0.82431424,  1.18087291, -1.6913601 ],
       [ 0.68236787, -1.59315436, -0.22465207,  0.24605762],
       [-0.91714414,  0.45914265, -0.45491117, -0.17439579]])

In [20]:
np.random.randint(1,100,10)

array([69, 32, 80, 32, 51, 89, 36, 56, 57, 84])

In [21]:
np.random.randint(50,70,(4,4))

array([[63, 52, 61, 59],
       [60, 62, 65, 60],
       [61, 51, 64, 59],
       [51, 62, 51, 58]])

In [22]:
array_arange = np.arange(16)

In [23]:
array_ranint = np.random.randint(0,100,10)

In [24]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
array_ranint

array([ 0, 21,  6, 63, 14, 74, 48, 37, 17,  6])

In [26]:
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
array_ranint.max()

74

In [28]:
array_ranint.min()

0

In [29]:
# find index of max and min numbers of numpy array
array_ranint.argmin()

0

In [30]:
array_ranint.argmax()

5

In [31]:
array_arange.shape

(16,)

In [32]:
array_arange.size

16

In [33]:
array_arange.dtype

dtype('int64')

In [34]:
array_1d = np.array([1,2,3,4,5])

In [35]:
array_1d, array_1d[0:2]

(array([1, 2, 3, 4, 5]), array([1, 2]))

In [36]:
array_2d = np.arange(24)

In [39]:
array_2d = array_2d.reshape(6,4)

In [40]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [41]:
array_2d[2][3]

11

In [42]:
array_2d[2,3]

11